---
title: "Part 1 - stringr functions"
author: "Alex Ehrens"
date: "2/22/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
```

### Detect string patterns with `str_detect()`

```{r}
vec <- c(" A Unicorn      Fish", "add    cornmeal", "French FRIES", "acorn Squash")

str_detect(vec, pattern = "corn")
```

```{r}
walk_subset <- starwars %>% 
  filter(str_detect(name, pattern = "walk")) # looks for and filters for rows containing the pattern "walk" in the name column

# Use str_subset() combines filter and str_detect into one thing
```

### Replace a string pattern with something else

`str_replace()` to replace an existing string pattern with something else
```{r}
vec_bren <- str_replace(vec, pattern = "corn", replacement = "COOL")

vec_bren
```

replace the pattern "Sky" with the pattern "TORNADO"
```{r}
sw_tornado <- starwars %>% 
  mutate(name = str_replace(name, pattern = "Sky", replacement = "TORNADO"))
```

## Use `str_trim()` to remove excess leading and trailing whitespace

```{r}
str_trim(vec) # removes leading/trailing white space

str_squish(vec) # removes any excess white spaces
```

```{r}
str_detect(vec, pattern = "Corn") # r is case sensitive
```

- `str_to_*()`


```{r}
str_to_lower(vec) # changes all to lower case

str_to_upper(vec) # changes to upper case

str_to_title(vec) # changes all words to title case (first upper, rest lower)
```

Using these in combination:
```{r}
sw_combo <- starwars %>% 
  filter(str_detect(name, pattern = "Darth")) %>% 
  mutate(name = str_replace(name, pattern = "Darth", replacement = "LLAMA")) %>% 
  mutate(name = str_to_lower(name))
```

